"""scan name unique to false

Revision ID: 07c2a6d290ff
Revises: a7fd8562c143
Create Date: 2024-05-05 18:54:32.751006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c2a6d290ff'
down_revision = 'a7fd8562c143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_constraint('scan_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.create_unique_constraint('scan_name_key', ['name'])

    # ### end Alembic commands ###
