"""create scan_ready

Revision ID: a7fd8562c143
Revises: 7ecb022da538
Create Date: 2024-05-05 18:44:08.655655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7fd8562c143'
down_revision = '7ecb022da538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ready', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('ready')

    # ### end Alembic commands ###
